#### Data Encoding 
1. Nominal/OHE Encoding 
2. Label and Ordinal Encoding 
3. Target Guided Ordinal Encoding

### 1. Norminal/OHE Encoding
one hot encoding(OHE), also known as nominal encoding, is a technique used to represent categorical data as numerical data,which is more suitable for machine learning algorithm. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable 'color' with three possible values(red,green,blue), we can represent it one hot encoding as follows.

1. Red:[1,0,1]
2. Green:[0,1,0]
3. Blue:[0,0,1]

In [2]:
# Data Encoding - Converting Categorical data into Numerical Data
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Create a simple Dataframe
df = pd.DataFrame({
    'color': ['red','blue','green','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
# Create an instance of Onehotencoder
encoder = OneHotEncoder()

In [8]:
# Perform fit and Transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [11]:
import pandas as pd
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
# for any new data
encoder.transform([['blue']]).toarray()

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in a alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable 'color' with three possible values(red,green,blue),we can represent it using label encoding as follows.
1. Red : 1
2. Green: 2
3. Blue: 3

In [15]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [17]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [18]:
lbl_encoder.fit_transform(df[['color']])

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [20]:
lbl_encoder.transform([['red']])

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [22]:
lbl_encoder.transform([['blue']])

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [23]:
lbl_encoder.transform([['green']])

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

#### Ordinal encoding 
it is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, If we have a categorical variable 'education level' with 4 possible values(high school,college,graduate,post-graduate), we can represent it using ordinal encoding as follows.

1. High school: 1
2. College : 2
3. Graduate : 3
4. Post-graduate : 4

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
# Create a sample dataframe with an ordinal variable 
df = pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [27]:
# Create an instance of OrdinalEncoder and then fit_transform

encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [28]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [29]:
# give new data 
encoder.transform([['large']])

d:\Learning Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[2.]])

### Target Guided Ordinal Encoding 
it is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variablewith a numerical value based on the mean or median of the target variable for that category. This Creates a monotonic relationship b/w the categorical variable and the target variable, which can improve the predictive power of our model.

In [33]:
import pandas as pd

#Create a dataframe with a categorical variable and a target variable 

df = pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200,150,300,250,180,320]
})

df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [36]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [37]:
df['city_encoded'] = df['city'].map(mean_price)

In [39]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0