In [47]:
import numpy as np 
import pandas as pd

In [48]:
# Series is 1D and DataFrame are 2D objects

In [49]:
#we can have multiple index? 
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [50]:
#problem ?- we have to all both the index such asn a['cse',2019]
# a['cse']

In [51]:
#solution -> multiindex series(also known as Hierarchical Indexing)
#multiple index levels within a single index

In [52]:
# How to create multiindex object 
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels
multiindex.levels[0] #branch 
multiindex.levels[1] #years
# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [53]:
#creating a series with multiindex objects
s = pd.Series([1,2,3,4,5,6,7,8],index = multiindex)
print(s)

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [54]:
#how to fetch items from such a Series
s['cse']
s[('cse',2020)]

np.int64(2)

In [55]:
# unstack - is use to convert a multiindex series into dataframe 
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [56]:
# stack - The stack() method pivots the columns of a DataFrame into its index, creating a multi-level index.
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [57]:
#Multiindex DataFrame  3D data -> 2D data
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [58]:
branch_df1.loc['cse']
branch_df1.loc['ece']
branch_df1['avg_package']
branch_df1['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [59]:
# multiindex df from columns perspective
# 3D data
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)    #note - from_product - do cartesian product

print(branch_df2)

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [60]:
branch_df2['delhi']
branch_df2['mumbai']
branch_df2['mumbai']['avg_package']
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [61]:
# Multiindex dataframe in terms of both columns and index
#4D data 
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

print(branch_df3)

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

### Stacking and unststacking

In [62]:
#unstack
branch_df1.unstack()
branch_df1.unstack().unstack()
branch_df2.unstack()

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    0
                     2021    0
                     2022    0
dtype: int64

In [63]:
#stack
branch_df1.unstack().stack()
branch_df1.stack()

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\2634381941.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

### Working with multiindex dataFrames

In [64]:
#head and tail
branch_df3.head()
branch_df3.tail()
#shape
branch_df3.shape
#info
branch_df3.info()
#duplicated 
branch_df3.duplicated()
#isnull 
branch_df3.isnull()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 932.0+ bytes

               delhi               mumbai
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [65]:
# Extracting rows single
branch_df3.loc[('cse',2022)]

delhi   avg_package    7
        students       8
mumbai  avg_package    0
        students       0
Name: (cse, 2022), dtype: int64

In [66]:
#Extracting multiple rows
branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [67]:
# using iloc
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [68]:
# Extracting cols
branch_df3['delhi']
branch_df3['delhi']['students']
#using iloc
branch_df3.iloc[:,1:3]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [69]:
# Extracting both
branch_df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [70]:
# sort index
# both -> descending -> diff order
# based on one level
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=0,ascending=[False])
branch_df3.sort_index(level=1,ascending=[False])

               delhi               mumbai
         avg_package students avg_package students
cse 2022           7        8           0        0
ece 2022          15       16           0        0
cse 2021           5        6           0        0
ece 2021          13       14           0        0
cse 2020           3        4           0        0
ece 2020          11       12           0        0
cse 2019           1        2           0        0
ece 2019           9       10           0        0

In [71]:
# multiindex dataframe(col) -> transpose-> rows-column , column - rows
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [72]:
#swaplevels 
branch_df3.swaplevel()
branch_df3.swaplevel(axis = 1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

### long vs Wide Data

Wide format is where we have a single row for every data point with multiple columns to hold the values of various attributes.

Long format is where, for each data point we have as many rows as the number of attributes and each row contains the value of a particular attribute for a given data point.

In [73]:
# melt -> wide data format to long data format
# wide to long
pd.DataFrame({'cse':[120]}).melt()

pd.DataFrame({'cse':[123],'it':[100],"mech":[30]}).melt()

pd.DataFrame({'cse':[123],'it':[100],"mech":[30]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           123
1     it           100
2   mech            30

In [74]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

In [75]:
# melt() -> melt() operation on real world example
death = pd.read_csv(r'D:\Learning Data Science\Dataset\time_series_covid19_deaths_global.csv')
confirm = pd.read_csv(r"D:\Learning Data Science\Dataset\time_series_covid19_confirmed_global.csv")

In [76]:
death.head()
death.shape
confirm.head()
confirm.shape

(289, 1081)

In [77]:
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')
# id_var is help us to not convert column to rows

In [78]:
death.head()
confirm.head()

  Province/State Country/Region       Lat       Long     date  num_cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20          0
1            NaN        Albania  41.15330  20.168300  1/22/20          0
2            NaN        Algeria  28.03390   1.659600  1/22/20          0
3            NaN        Andorra  42.50630   1.521800  1/22/20          0
4            NaN         Angola -11.20270  17.873900  1/22/20          0

In [79]:
#merge death and confirm dataframe 
confirm.merge(death,on=['Province/State','Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]

### Pivot Table

The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.

In [80]:
import numpy as np
import pandas as pd
import seaborn as sns

In [81]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [82]:
#Q- bill paid by male and female 
df.groupby('sex')[['total_bill']].mean()

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\4253905264.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [83]:
#bill paid by smoker and non smoker  male and female 
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\3446517443.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [84]:
#use pivot table 
# The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.
df.pivot_table(index='sex',columns='smoker',values='total_bill')

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\3436804141.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [85]:
# Aggregate function on pivot table 
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum')
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='count')
df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\662893369.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='sum')
C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\662893369.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='count')
C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\662893369.py:4: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker',values='total_bill',aggfunc='std')

smoker       Yes        No
sex
Male    9.911845  8.726566
Female  9.189751  7.286455

In [90]:
#Multidimensional 
df.pivot_table(index = ['sex','smoker'],columns=['day','time'],values='total_bill')
df.pivot_table(index = ['sex','smoker'],columns=['day','time'])

C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\292856109.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = ['sex','smoker'],columns=['day','time'],values='total_bill')
C:\Users\Dell\AppData\Local\Temp\ipykernel_21572\292856109.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = ['sex','smoker'],columns=['day','time'])

                   size                                                   tip  \
day                Thur              Fri              Sat       Sun      Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner     Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  3.058000
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  2.941500
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  2.990000
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  2.437083

                                                      total_bill         \
day                    Fri              Sat       Sun       Thur
time          Dinner Lunch Dinner    Dinner    Dinner      Lunch Dinner
sex    smoker
Male   Yes       NaN  1.90  3.246  2.879259  3.521333  19.171000    NaN
       No        NaN   NaN  2.500  3.256563  3.115349  18.486500    NaN
Female Yes       NaN  2.66  2.700  2.868667  3.500000  19.218571    NaN
       No        3.0  3.00  3.250  2.724615  3.329286  15.899167  18.78


day                  Fri                Sat        Sun
time               Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     11.386667  25.892  21.837778  26.141333
       No            NaN  17.475  19.929063  20.403256
Female Yes     13.260000  12.200  20.266667  16.540000
       No      15.980000  22.750  19.003846  20.824286