### Some Important Series Method

In [5]:
import numpy as np
import pandas as pd

In [8]:
#read csv file of 'subs dataset'  
subs = pd.read_csv(r"D:\Campusx\pandas-CX dataset\subs.csv")
subs

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Campusx\\pandas-CX dataset\\subs.csv'

In [ ]:
#read csv file 'kohli_ipl' 
vk = pd.read_csv(r"D:\Campusx\pandas-CX dataset\kohli_ipl.csv")
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
#read csv file 'bollywood' 
movies = pd.read_csv(r"D:\Campusx\pandas-CX dataset\bollywood.csv")
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [ ]:
#astype - change the datatype 
import sys
sys.getsizeof(vk)

3604

In [ ]:
vk.astype('int16')
sys.getsizeof(vk)
sys.getsizeof(vk.astype('int16'))

1024

In [ ]:
# between 
#.between() is a method of Series, not DataFrame. 

vk[vk.between(51,99)].size #This returns the count of values in vk that are between 51 and 99 (inclusive)
# ---
vk[vk['column_name'].between(51, 99)].shape[0] 
'''- Replace 'column_name' with the actual column you're filtering.
- .shape[0] gives the number of rows that match the condition.
'''

AttributeError: 'DataFrame' object has no attribute 'between'

In [ ]:
#clip
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
#drop Duplicates
temp = pd.Series([1,1,2,2,3,3,4,4])
temp.drop_duplicates() #drop 1st occurence #by Default 
temp.drop_duplicates(keep='last') ##drop last occurence
temp.duplicated() #to check duplicate value exist or not
temp.duplicated().sum() #tells total duplicate value

4

In [ ]:
vk.duplicated().sum()
movies.drop_duplicates()

NameError: name 'vk' is not defined

In [ ]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp
temp.size #total values = 10
temp.count() #give nit null values which is 7

7

In [ ]:
#isnull - to check missing or null values
vk.isnull()
vk.isnull().sum()
# temp.isnull().sum()

match_no    0
runs        0
dtype: int64

In [ ]:
#dropna- remove missing values or null values
temp.dropna()

0     1.0
1     2.0
2     3.0
4     5.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [ ]:
#fillna - use to fill null or missing values 
temp.fillna(0) #fill all the missing values with 0
temp.fillna(temp.mean()) ##fill all the missing values with mean value

0     1.0
1     2.0
2     3.0
3     5.0
4     5.0
5     6.0
6     5.0
7     8.0
8     5.0
9    10.0
dtype: float64

In [ ]:
#isin 
vk[(vk == 49) | (vk == 99)]
#use isin
vk[vk.isin([49,99])]

     match_no  runs
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
..        ...   ...
210       NaN   NaN
211       NaN   NaN
212       NaN   NaN
213       NaN   NaN
214       NaN   NaN

[215 rows x 2 columns]

In [ ]:
vk
new = vk.head()
new[1] = 1
new = vk.head().copy() 
new[1] = 100
vk

C:\Users\Dell\AppData\Local\Temp\ipykernel_4080\3318594881.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[1] = 1

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
##copy
new = vk.head().copy()
new
new[1] = 100
new

   match_no  runs    1
0         1     1  100
1         2    23  100
2         3    13  100
3         4    12  100
4         5     1  100